version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Auto dependency update]"
    groups:
      dependencies:
        patterns:
          - "*"
