inputs:
  access_token:
    required: true
  file_id:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        access_token: ${{ inputs.access_token }}
        file_id: ${{ inputs.file_id }}
      run: |
        http_code=$(curl --write-out '%{http_code}' --silent --output /dev/null -L -X GET \
        https://www.googleapis.com/drive/v3/files/$file_id?access_token=$access_token&alt=media)
        
        echo "Http code: $http_code"
        if [[ $http_code -ne 200 ]]; then
            echo "Error when downloading the file from Google Drive"
            exit 1
        fi
        
