on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Destination mail'
        required: true

jobs:
  build-pdf:
    name: "Build PDF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

      # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          echo "Install dependencies..."
          npm ci

      - uses: ./.github/actions/request-google-token
        name: Request Google Token
        id: request_google_token
        with:
          private_key_id: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
          private_key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          service_account_mail: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          scope: "https://www.googleapis.com/auth/drive.file"

      - uses: ./.github/actions/download-file-google-drive
        name: Download personal data
        with:
          access_token: ${{ steps.request_google_token.outputs.access_token }}
          file_id: "18ixC1EpMasuriA6XH5Gg9dbaiBNaFrPn"

      - name: Run
        run: |
          ls -l
          echo "Buil app..."
          npm run start &

#      - name: Run Selenium and download PDF
#        run: python download_pdf.py
#          selenium-standalone start

#      - name: Send mail
#        uses: dawidd6/action-send-mail@v3
#        with:
#          # Required mail server address if not connection_url:
#          server_address: smtp.gmail.com
#          # Server port, default 25:
#          server_port: 465
#          # Optional whether this connection use TLS (default is true if server_port is 465)
#          secure: true
#          # Optional (recommended) mail server username:
#          username: ${{secrets.MAIL}}
#          # Optional (recommended) mail server password:
#          password: ${{secrets.MAIL_PASSWORD}}
#          # Required mail subject:
#          subject: Github Actions job result
#          # Required recipients' addresses:
#          to: ${{ github.event.inputs.mail }}
#          # Required sender full name (address can be skipped):
#          from: GitHub Actions (CV)
#          # Optional plain body:
#          body: Build job of ${{github.repository}} completed successfully!
#          # Optional unsigned/invalid certificates allowance:
#          ignore_cert: true
#          # Optional attachments:
#          #          attachments: attachments.zip,git.diff,./dist/static/*.js
#          # Optional priority: 'high', 'normal' (default) or 'low'
#          priority: normal
