on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Destination mail'
        required: true

jobs:
  build-pdf:
    name: "Build PDF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          echo "Install dependencies..."
          npm ci  

      - name: Build And run
        run: |
          echo "Buil app..."
          npm run start
      - name: Open Selenium
        run: |
          echo "Open Selenium..."
#          selenium-standalone start

#      - name: Send mail
#        uses: dawidd6/action-send-mail@v3
#        with:
#          # Required mail server address if not connection_url:
#          server_address: smtp.gmail.com
#          # Server port, default 25:
#          server_port: 465
#          # Optional whether this connection use TLS (default is true if server_port is 465)
#          secure: true
#          # Optional (recommended) mail server username:
#          username: ${{secrets.MAIL}}
#          # Optional (recommended) mail server password:
#          password: ${{secrets.MAIL_PASSWORD}}
#          # Required mail subject:
#          subject: Github Actions job result
#          # Required recipients' addresses:
#          to: ${{ github.event.inputs.mail }}
#          # Required sender full name (address can be skipped):
#          from: GitHub Actions (CV)
#          # Optional plain body:
#          body: Build job of ${{github.repository}} completed successfully!
#          # Optional unsigned/invalid certificates allowance:
#          ignore_cert: true
#          # Optional attachments:
#          #          attachments: attachments.zip,git.diff,./dist/static/*.js
#          # Optional priority: 'high', 'normal' (default) or 'low'
#          priority: normal
